# baseURL
@baseURL = http://localhost:8001/api
@userId = {userId}
@token = 5|D2OrKnzf1g0549UBkzil4sBahgvc7NP4Lfn3wCxy646443f5

###
# Login User
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "johndoe@email.com",
    "password": "StrongPassword@1234"
}

###
# Create Guest User
POST {{ baseURL }}/guest
Content-Type: application/json

###
# Create User
POST {{ baseURL }}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "John Doe",
    "born_date": "1999-01-01",
    "address": "Any Address",
    "cpf_cnpj": "71651383820",
    "email": "johndoe@email.com",
    "password": "StrongPassword@1234"
}

###
# Find User By Id
GET {{ baseURL }}/users/{{ userId }}

###
# Find User Items In Cart By Id
GET {{ baseURL }}/users/{{ userId }}/cart-items
